//
//  CEESessionDescriptor.c
//  Cymbols
//
//  Created by qing on 2020/7/14.
//  Copyright © 2020 Lazycatdesign. All rights reserved.
//

char* init_descriptor_template = "\"window\":{\"frame\":\"{{739, 270}, {840, 782}}\",\"IDSessionView\":{\"size\":\"{840, 782}\",\"subviews\": [{\"IDToolbarView\":{\"size\":\"{840, 32}\",\"shown\":\"YES\"}},{\"IDSessionSplit0View\":{\"size\":\"{840, 704}\",\"subviews\": [{\"collapsed\": \"YES\",\"IDSessionSymbolView\": {\"size\":\"{250, 739}\",\"subviews\":[]}},{\"collapsed\": \"NO\",\"IDSessionSourceView\":{\"size\":\"{839, 704}\",\"subviews\": [{\"IDSessionSplit1View\":{\"size\":\"{839, 704}\",\"subviews\": [{\"collapsed\": \"NO\",\"IDSessionFrameManagerView\":{\"size\":\"{839, 704}\",\"subviews\":[{\"##IDSessionFrameView##\":{\"frame\":\"{{0, 0}, {839, 704}}\"}}]}},{\"collapsed\": \"YES\",\"IDSessionContextView\": {\"size\":\"{1120, 300}\",\"subviews\":[]}}]}}]}},{\"collapsed\": \"YES\",\"IDSessionReferenceView\": {\"size\":\"{250, 739}\",\"subviews\":[]}},{\"collapsed\": \"YES\",\"IDSessionFilePathView\": {\"size\":\"{250, 739}\",\"subviews\":[]}}]}}]}}";
char* open_file_descriptor_template = "\"window\":{\"frame\":\"{{739, 270}, {840, 782}}\",\"IDSessionView\":{\"size\":\"{840, 782}\",\"subviews\": [{\"IDToolbarView\":{\"size\":\"{840, 32}\",\"shown\":\"NO\"}},{\"IDSessionSplit0View\":{\"size\":\"{840, 704}\",\"subviews\": [{\"collapsed\": \"YES\",\"IDSessionSymbolView\": {\"size\":\"{250, 739}\",\"subviews\":[]}},{\"collapsed\": \"NO\",\"IDSessionSourceView\":{\"size\":\"{839, 704}\",\"subviews\": [{\"IDSessionSplit1View\":{\"size\":\"{839, 704}\",\"subviews\": [{\"collapsed\": \"NO\",\"IDSessionFrameManagerView\":{\"size\":\"{839, 704}\",\"subviews\":[{\"##IDSessionFrameView##\":{\"frame\":\"{{0, 0}, {839, 704}}\"}}]}},{\"collapsed\": \"YES\",\"IDSessionContextView\": {\"size\":\"{1120, 300}\",\"subviews\":[]}}]}}]}},{\"collapsed\": \"YES\",\"IDSessionReferenceView\": {\"size\":\"{250, 739}\",\"subviews\":[]}},{\"collapsed\": \"YES\",\"IDSessionFilePathView\": {\"size\":\"{250, 739}\",\"subviews\":[]}}]}}]}}";
